title: ToFile
executor:
  name: nodejs
  options:
    entry: index.ts
inputs_def:
  - handle: sharp
    json_schema:
      contentMediaType: oomol/var
      type:
        - string
        - number
        - integer
        - boolean
        - object
        - array
        - "null"
      ui:widget: any
  - handle: name
    json_schema:
      type: string
  - handle: address
    json_schema:
      type: string
      ui:widget: dir
  - handle: formate
    json_schema:
      type: string
      enum:
        - png
        - jpeg
        - webp
outputs_def:
  - handle: file_address
    json_schema:
      type: string
render: ./oo-render/dist/render.mjs
